//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "author")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub image: String,
    pub url: String,
    #[sea_orm(has_many)]
    pub recipes: HasMany<super::recipe::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
