//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "ingredient_unit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ingredient_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub unit_id: String,
    #[sea_orm(
        belongs_to,
        from = "ingredient_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub ingredient: HasOne<super::ingredient::Entity>,
    #[sea_orm(
        belongs_to,
        from = "unit_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub unit: HasOne<super::unit::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
