//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod author;
pub mod image;
pub mod ingredient;
pub mod ingredient_unit;
pub mod preparation;
pub mod recipe;
pub mod unit;
