//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::author::Entity as Author;
pub use super::ingredient::Entity as Ingredient;
pub use super::ingredient_unit::Entity as IngredientUnit;
pub use super::preparation::Entity as Preparation;
pub use super::recipe::Entity as Recipe;
pub use super::unit::Entity as Unit;
