//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub description: String,
    pub prep_time: Option<String>,
    pub cook_time: Option<String>,
    pub total_time: String,
    pub author_id: i64,
    pub serves: i64,
    pub e_tag: String,
    pub organisation_id: String,
    pub locale: String,
    pub created_at: DateTimeUtc,
    pub modified_at: DateTimeUtc,
    pub published_at: DateTimeUtc,
    pub created_by_id: String,
    pub steps: Json,
    pub ingredients: Json,
    pub is_custom: bool,
    pub exposed_id: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "author_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub author: HasOne<super::author::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
