//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "recipe")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub description: String,
    pub prep_time: Option<String>,
    pub cook_time: Option<String>,
    pub total_time: String,
    pub author_id: i32,
    pub serves: i32,
    pub e_tag: String,
    pub organisation_id: String,
    pub locale: String,
    pub created_at: DateTime,
    pub modified_at: DateTime,
    pub published_at: DateTime,
    pub created_by_id: String,
    pub steps: Json,
    pub ingredients: Json,
    pub is_custom: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::author::Entity",
        from = "Column::AuthorId",
        to = "super::author::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Author,
}

impl Related<super::author::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Author.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
