//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "unit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub abbreviation: Option<String>,
    pub dimension_id: Option<String>,
    pub measurement_system_id: Option<String>,
    #[sea_orm(has_many, via = "ingredient_unit")]
    pub ingredients: HasMany<super::ingredient::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
