//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "unit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub abbreviation: Option<String>,
    pub dimension_id: Option<String>,
    pub measurement_system_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ingredient_unit::Entity")]
    IngredientUnit,
}

impl Related<super::ingredient_unit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientUnit.def()
    }
}

impl Related<super::ingredient::Entity> for Entity {
    fn to() -> RelationDef {
        super::ingredient_unit::Relation::Ingredient.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::ingredient_unit::Relation::Unit.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
